### PR TITLE
Switch to TypeScript

### PR DESCRIPTION
**Pull request by pmeinhardt**

### CODE REVIEW

**Comment by pmeinhardt** [comment]
I converted our code to TypeScript and made a lot of improvements along the way. A large portion of @tessi's work on the formatter made it in here. I think this will be hard to review. I would suggest checking out this branch and then test-riding a local build for some time. ✌️ 

@tessi & @klappradla 💚

**Comment by klappradla** [comment]
First suspicious encounter while test-riding 🚲 

The Jira adapter returns the same result for `branch`, `command` and `message`: always the `message`.

See this quick onehanded demo with one foot out the door 🍿 

ticktick

**Comment by pmeinhardt** [comment]
> First suspicious encounter while test-riding 🚲
> 
> The Jira adapter returns the same result for `branch`, `command` and `message`: always the `message`.
> 
> See this quick onehanded demo with one foot out the door 🍿
> 
> ticktick

Can you check the values for the commit, branch and command templates on the settings page?

**Comment by klappradla** [comment]
> Can you check the values for the commit, branch and command templates on the settings page?

I have the following config:

- autoformat: off
 
- message:

  ```
  [{id}] {title}

  [{id}]({url})
  ```

- branch: _(default I think)_

  ```
  {type | slugify}/{id | slugify}-{title | slugify}
  ```

- command _(default I think)_

  ```
  git checkout -b {branch | shellquote} && git commit --allow-empty -m {commit | shellquote}
  ```

### Update 🚨

What I did not realize in https://github.com/bitcrowd/tickety-tick/pull/314#issuecomment-916168010 as I had to put it down so fast: the message button is the only one that actually works! The other buttons don't populate the clipboard.

**Review by klappradla — APPROVED** [review]
Testing the 2nd beta now - running smooth since a week 🧘

Let's ⛵

**Pull request merged**
