### PR TITLE
[#97] Fix icon loading on about view

### PR DESCRIPTION
**Pull request by pmeinhardt**
Remove the icon as a simple way out.

### CODE REVIEW

**Comment by tessi** [comment]
Hmmm can we inline the icon as a data-url instead?

**Comment by pmeinhardt** [comment]
Absolutely @tessi. This was my initial thought. But then I realized I'll need to introduce another webpack loader and configure it and thought I'd see if I can get by without that 😁

I'll inline it right away if you prefer 🙂

**Comment by pmeinhardt** [comment]
Fixed it now @tessi — I'll just have another look at the configuration and whether we could use this to explicitly import icons for generating the manifest etc.

image

**Comment by pmeinhardt** [comment]
This is good to go from my side.

**Pull request merged**
