### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pmeinhardt**

### CODE REVIEW

**Comment by pmeinhardt** [comment]
Open: Update `eslint-config-bitcrowd-react` to version `12.0.0` once https://github.com/bitcrowd/javascript/issues/10 is resolved.

**Comment by bitboxer** [comment]
@pmeinhardt does "open" mean I should not merge this? Or is this okay to merge?

**Comment by pmeinhardt** [comment]
Thanks for asking. I'd leave it open and use this PR to keep track of these changes – today's rather busy, so I hope I can get around to it some time this week.

**Comment by pmeinhardt** [comment]
@weiland told me he's already working on https://github.com/bitcrowd/javascript/issues/10.

After that's all good and done, I'll update this PR and give you another nudge @bitboxer.

**Comment by bitboxer** [comment]
@pmeinhardt I added a work in progress label to this. Remove it and nudge me if done.

**Comment by pmeinhardt** [comment]
@bitboxer Nudge, nudge.

**Pull request merged**
