### PR TITLE
[#165] Unable to copy default value in settings 

### PR DESCRIPTION
**Pull request by pmeinhardt**
preview

### CODE REVIEW

**Comment by pmeinhardt** [comment]
@maltoe and @andreasknoepfle thank you both for your feedback 👍 
I've quickly put together a hacky version of a solution.

Take a look or - better - take it for a spin and let me know what you think 👋

**Comment by pmeinhardt** [comment]
Okay, so here's an updated version with tests. The behavior seems intuitive to me at least 😁

**Comment by maltoe** [comment]
@pmeinhardt Tested, works for me, and intuitive enough. Possibly increase the font size of the default just a tiny bit? Feel free to ingore.

**Comment by pmeinhardt** [comment]
I've bumped up the base font size for the options page a little bit. For some reason there's a huge gap in the rendered font sizes in Firefox and Chrome, so bumping it up even more makes it look super-awkward in Chrome. I tried to hit some middleground there that still seems somewhat reasonable.

preview

Thanks for your feedback @maltoe 👍

**Comment by pmeinhardt** [comment]
This'll go into the `3.2` release: https://github.com/bitcrowd/tickety-tick/milestone/7?closed=1
@andreasknoepfle, maybe you can find a quiet moment today to publish? ✌️

**Pull request merged**
