### PR TITLE
[#154] Github tickety-tick issues seem to not work anymore

### LINKED ISSUE #154: Github tickety-tick issues seem to not work anymore
Screenshot 2019-04-12 at 11 21 39
Maybe github changed their markup.

### PR DESCRIPTION
**Pull request by bitboxer**
Closes #154 .

### CODE REVIEW

**Comment by pmeinhardt** [comment]
@andreasknoepfle, you opened the issue. Do you have time to try out this fix?

I am currently working on an older GitHub Enterprise… 🤔 
On that matter, the fix will probably break compatibility for that.
I am wondering whether we could support both versions @bitboxer?

✌️

**Comment by bitboxer** [comment]
Supporting all versions? Yeah, possible, but shouldn't the company update that security hole filled outdated enterprise install :trollface: ?

**Comment by pmeinhardt** [comment]
> Supporting all versions? Yeah, possible, but shouldn't the company update that security hole filled outdated enterprise install :trollface: ?

Of course they [SHOULD](https://tools.ietf.org/html/rfc2119#section-3)™️ 😁 

In the meantime, I could imagine something along the lines of:

```javascript
// Element classes on GitHub have slightly changed over time.
// To maintain support for some older GitHub Enterprise instances,
// the adapter will attempt different versions of selectors.

const selectors = {
  default: {
    issuesPage: '.js-check-all-container .js-issue-row.selected',
    issuePage: '.js-issues-results .gh-header-number',
    // …
  },
  legacy: {
    issuesPage: '…',
    // …
  },
};

function attempt(loc, doc, selectors) {
  // …"old" scan code with selectors replaced here
}

async function scan(loc, doc) {
  const tickets = attempt(loc, doc, selectors.default);
  if (tickets.length > 0) return tickets;
  return attempt(loc, doc, selectors.legacy);
}
```

…and then the tests would be parameterized similarly:

```javascript
import scan, { selectors } from './github';

Object.keys(selectors).forEach(variant => {
  describe(`github adapter (${variant})`, () => {
    // …
  });
});
```

**Comment by pmeinhardt** [comment]
Ah, and somehow the `yarn.lock` file seems to have changed here 🤔
Ideally exclude this from this PR.

Thanks ✌️

**Comment by bitboxer** [comment]
will update this on the weekend

**Comment by pmeinhardt** [comment]
Awesome! Thanks a lot @bitboxer 🙇

**Comment by bitboxer** [comment]
@pmeinhardt it is updated now. Please review :bowtie:

**Comment by pmeinhardt** [comment]
One more wish @bitboxer: There's a conflict because of the intermediate `yarn.lock` changes. Could you rebase (+squash) and update the PR. Thanks 🙇

**Comment by bitboxer** [comment]
Done.

**Comment by pmeinhardt** [comment]
Neat ✨ Thank you! 🙂

**Pull request merged**
