### PR TITLE
[#159] Add a screencast to the readme

### PR DESCRIPTION
**Pull request by klappradla**
#159

Update README with a short screencast of a possible workflow using Tickety-Tick 🍿

### CODE REVIEW

**Review by ammancilla — APPROVED** [review]
🎥

**Review by planktonic — APPROVED** [review]
🪄

**Comment by klappradla** [comment]
Oh, that's great news @pmeinhardt 👀 
I just tried `.webm` - which isn't supported... Will have a quick look into how an `mp4` or `mov` turns out.

**Comment by klappradla** [comment]
Ok, took me a minute to figure out @pmeinhardt: embedding videos only works when uploaded via drag & drop 😂 

Fair enough 🤷 Updated with an mp4 version.

**Pull request merged**
