### PR TITLE
Tickety-Tick Revised

### PR DESCRIPTION
**Pull request by pmeinhardt**
Opening a PR here to track open points that I would like to work on and hear your thoughts.

- [x] set up build using gulp, remove bower (addresses issue #7)
- [x] use Sass for generating stylesheets
- [x] set up linting and de-lint code (addresses issue #9, makes #10 obsolete)
- [x] unify Chrome and Firefox extension code
- [x] factor out ticket system compatibility
- [x] remove in-code browser switches (configured from the main, popup entry point)
- [x] use React for the popup user interface instead of jQuery
- [x] slightly rework interface (now directly shows a list with copy buttons for each item, before a separate navigation step was needed)
- [x] generate summaries of open tickets for use in joblogs (as requested by @andreasknoepfle)
- [x] only build Chrome/Firefox(/Opera) extension once
  - currently the `firefox` directory is a symlink and is still build separately (seems superfluous now)
  - we can probably save some time and only create on build for both
  - just need to think of a good name for the source and dist subdirectories then
- [x] check whether the plugin also works in Opera/Microsoft Edge as suggested by [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)
  - chrome-extension works in Opera as is, MS Edge needs at least some changes to the `manifest.json` and then some more in the actual code
- [ ] get rid of jQuery for the ticket system adapters?
  - this can probably be done by using the native `node.querySelector/querySelectorAll`
  - maybe factor out the helpers into `src/common/adapters/helpers.js`
  - currently, it looks like the 4 tiny helper functions for `has(selector, doc)`, `text(selector, doc)`, `val(selector, doc)` and `trim(str)` would be enough to support the current selection of ticket systems
  - for these we might not need good ol' jQuery (though I don't really mind)
- [x] implement an adapter for Trello
- [x] allow GitHub adapter to detect multiple tickets when on issues index page (has checkboxes for selecting in Chrome at least)
- [x] find and use a library for translating special characters (`äöüß…éñ`) in branch names (see `src/common/popup/utils/format.js`) (iconv `//TRANSLIT`? [node-transliteration #slugify](https://tonicdev.com/57d09d3dd1cbc51400a5a326/57d09d3dd1cbc51400a5a327)?)
- [x] polish the UI a little more?
  - [x] bring back the colors?
  - [x] nicer buttons for copying the commit messages and branch names (SVG icons?)
- [x] create crisp icons for every size (currently some of the smaller sizes are a little blurry)
- [x] update the README
  - [x] update build/lint/test instructions
  - [x] Firefox section needs to be updated (now same as Chrome)
  - [x] update section on supported ticket tracking systems (add Trello?)
  - [ ] add link to official Opera extension and state that Opera is supported
  - [x] create new screenshot (when design is finished)
- [x] testing
  - one of the main reasons for the revision was testability
  - therefore I would really like to add tests
  - [x] test React components
  - [x] test ticket system adapters
  - [x] set up `.travis.yml`
  - [x] add travis badge to README
- [ ] republish, yay (Chrome, Firefox, Opera)

### CODE REVIEW

**Comment by bitboxer** [comment]
Btw: what about PR #10 ? Can this be deleted because of this?

**Comment by pmeinhardt** [comment]
Yup, thanks @bitboxer 😄

**Comment by bitboxer** [comment]
I activated the build on travis for this repo 👍

**Comment by pmeinhardt** [comment]
Very nice, thanks 👍

**Comment by pmeinhardt** [comment]
Microsoft Edge seems to require a few changes to get this working. Might do that in a separate PR if it doesn't take too much work (5 mins didn't do it right now).

**Comment by pmeinhardt** [comment]
@planktonic, could I ask you to take a look at this and maybe come up with some good-looking styles for this when you have a quiet moment? This is the last thing missing for a new release I think (the tracker adapters can probably be improved but these are now clearly separated units so we can still improve these later on, plus they're at least as reliable as the current implementation).

In particular I would like to bring back some of the original color `#c32f34`, i.e. for the buttons and links maybe, because these are the components you can interact with. I thought that the copy-buttons in the main list could simply be a [`comment`](https://octicons.github.com/icon/comment/) and a [`git-branch` icon](https://octicons.github.com/icon/git-branch/) (for the commit message and branch-name button).

Some of the text and component spacing can probably be improved as well.

Feel free to reach out if you'd like to discuss ideas/options or if you have any questions.

**Comment by bitboxer** [comment]
👍 for getting this out of the door soon

**Comment by pmeinhardt** [comment]
Hey @bitboxer, can you take please a look at this when you have time? There are some tiny style issues in Safari (button corners) and the popup height adjustments are not as nice in Firefox/Safari as they are in Chrome/Chromium but I think that'll work.

Cheers 🎈

**Comment by planktonic** [comment]
Hey @pmeinhardt, sorry, I didn't get to this last week — does this still need some styling? (on a separate branch now of course)

**Comment by pmeinhardt** [comment]
Hey @planktonic, no problem. I wasn't aware you're off to a conference visit then. At this risk of you not talking to me anymore, I simply plugged in a slimmed-down and customized bootstrap (Sass) so I could finish this off 😆

**Comment by planktonic** [comment]
🙈

**Pull request merged**
