### PR TITLE
[#43] Trying out yarn?

### PR DESCRIPTION
**Pull request by pmeinhardt**
Taking yarn for a spin: #43.

### CODE REVIEW

**Comment by bitboxer** [comment]
👍 will merge after you rebased it.

**Comment by bitboxer** [comment]
One little thing: what about the readme? Do you want to add yarn there?

**Comment by pmeinhardt** [comment]
Good point about the README. It's updated and I've also rebased this branch.

**Comment by bitboxer** [comment]
Thanks!

**Pull request merged**
