### PR TITLE
[#93] Update Jira adapter

### PR DESCRIPTION
**Pull request by nickgnd**
Related to this [comment](https://github.com/bitcrowd/tickety-tick/issues/93#issuecomment-506907513)

Now the Jira adapter returns the ticket description and URL in the commit body.

---

By @klappradla and me

### CODE REVIEW

**Comment by nickgnd** [comment]
@pmeinhardt mmhhh, good point!

Not really, we used 2 tickets as an example, one with and one without description.
The former had a multiline text with bullet points and it was perfectly copied in the commit body by `tickety-tick`, but we didn't check other tickets with more advanced markup.
We should definitely check 👍

**Comment by klappradla** [comment]
_(quickly rebasing this one on top of current `master` 🏓 )_

**Comment by klappradla** [comment]
Hm, I tried it out on a Jira issue with some more complex markup features including:
- bullet points
- code snippets
- images

The resulting commit message body indeed looks a bit weird, but maybe that's even ok for what we want (I adapted it a bit to be less verbose):

```
[#PROJECT-397] Create Opening Hours for Space…

…fails on Firefox


_Steps to reproduce_

- Open a Firefox browser
- Login as Admin
- Click Submit

_Expected Result_

Cafe should show newly added opening hours

_Actual Result_

Cafe shows ‘Closed’ for all days.

_Browser_

Firefox Quantum, 69.0.3 (64-bit)

_Console output_

{noformat}[info] POST
/admin/cafes/ec7ff5d9-8256-40fe-a1ce-2b4afefe336b/opening_hours [debug]
Processing with
CafeWeb.Admin.CafeController.update_opening_hours/2 Parameters:
%{"\_csrf_token" =>
...
[]{noformat}

_Picture of the form on FF_

!Thing\_·_Other
(3a47998e-5394-46e8-8f62-10fb01296944).png|width=633,height=693!

https://project.atlassian.net/browse/PROJECT-397
```

Is that usable?

**Comment by tessi** [comment]
I'd say it serves the purpose (giving a good start for a commit message which can then be refined).

Bullte points and maybe even headings are readable as-is. Images are useless (obviously in a text-only format) as well as these tags like `{noformat}`. But it should be easy enough to remove these manually.

**Comment by pmeinhardt** [comment]
Hey, sorry for the long delay @nickgnd. Somehow this slipped passed me. I've rebased, resolved conflicts and adjusted the formatting to satisfy the linter (config was updated slightly since the PR was opened). Thanks a lot 💚 

:shipit:

**Pull request merged**
